Dialog:
  - Id: <%= Atlas.Dialog('CONFIG') %>
    Prop: IPad
    TranslationBrackets: true
    $TextAlien:
      - Commander, this freighter's <TECHNOLOGY>DEEP SPACE SCANNING<> system can now be reconfigured. What should be changed?
    Options:
      - Name: <%= Atlas.Mod.LocKey('MENU_CONFIG_COST_E') %>
        $Text: Confirmed, scan costs set to ENABLED. Anything else, Commander?
        IsAlien: true
        MarkInteractionComplete: false
        KeepOpen: true
        EnablingConditionTest: AllFalse
        EnablingConditions:
          - $: GcMissionConditionStatLevel
            Stat: <%= Atlas.Stat('CFG_COST') %>
            Level: 0
            Test: Equal
        Rewards:
          - Id: <%= Atlas.Reward('CST_ON') %>
            RewardChoice: GiveAll
            List:
              - $: GcRewardModifyStat
                Stat: <%= Atlas.Stat('CFG_COST') %>
                ModifyType: Set
                Amount: 1
          # - <%= Atlas.Reward('REBOOT') %>

      - Name: <%= Atlas.Mod.LocKey('MENU_CONFIG_COST_D') %>
        $Text: Confirmed, scan costs set to DISABLED. Anything else, Commander?
        IsAlien: true
        MarkInteractionComplete: false
        KeepOpen: true
        EnablingConditionTest: AllFalse
        EnablingConditions:
          - $: GcMissionConditionStatLevel
            Stat: <%= Atlas.Stat('CFG_COST') %>
            Level: 1
            Test: Equal
        Rewards:
          - Id: <%= Atlas.Reward('CST_OFF') %>
            RewardChoice: GiveAll
            List:
              - $: GcRewardModifyStat
                Stat: <%= Atlas.Stat('CFG_COST') %>
                ModifyType: Set
                Amount: 0
          # - <%= Atlas.Reward('REBOOT') %>

      - Name: <%= Atlas.Mod.LocKey('MENU_CONFIG_TECH_E') %>
        $Text: Confirmed, technology requirements set to ENABLED. Anything else, Commander?
        IsAlien: true
        MarkInteractionComplete: false
        KeepOpen: true
        EnablingConditionTest: AllFalse
        EnablingConditions:
          - $: GcMissionConditionStatLevel
            Stat: <%= Atlas.Stat('CFG_TECH') %>
            Level: 0
            Test: Equal
        Rewards:
          - Id: <%= Atlas.Reward('TCH_ON') %>
            RewardChoice: GiveAll
            List:
              - $: GcRewardModifyStat
                Stat: <%= Atlas.Stat('CFG_TECH') %>
                ModifyType: Set
                Amount: 1
          # - <%= Atlas.Reward('REBOOT') %>

      - Name: <%= Atlas.Mod.LocKey('MENU_CONFIG_TECH_D') %>
        $Text: Confirmed, technology requirements set to DISABLED. Anything else, Commander?
        IsAlien: true
        MarkInteractionComplete: false
        KeepOpen: true
        EnablingConditionTest: AllFalse
        EnablingConditions:
          - $: GcMissionConditionStatLevel
            Stat: <%= Atlas.Stat('CFG_TECH') %>
            Level: 1
            Test: Equal
        Rewards:
          - Id: <%= Atlas.Reward('TCH_OFF') %>
            RewardChoice: GiveAll
            List:
              - $: GcRewardModifyStat
                Stat: <%= Atlas.Stat('CFG_TECH') %>
                ModifyType: Set
                Amount: 0
          # - <%= Atlas.Reward('REBOOT') %>

      - Name: <%= Atlas.Mod.LocKey('MENU_CONFIG_CHAT_E') %>
        $Text: Confirmed, chat notifications set to ENABLED. Anything else, Commander?
        IsAlien: true
        MarkInteractionComplete: false
        KeepOpen: true
        EnablingConditionTest: AllFalse
        EnablingConditions:
          - $: GcMissionConditionStatLevel
            Stat: <%= Atlas.Mod.Stat('CFG_CHAT') %>
            Level: 1
            Test: Equal
        Rewards:
          - Id: <%= Atlas.Reward('CHT_ON') %>
            RewardChoice: GiveAll
            List:
              - $: GcRewardModifyStat
                Stat: <%= Atlas.Mod.Stat('CFG_CHAT') %>
                ModifyType: Set
                Amount: 0
          # - <%= Atlas.Reward('REBOOT') %>

      - Name: <%= Atlas.Mod.LocKey('MENU_CONFIG_CHAT_D') %>
        $Text: Confirmed, chat notifications set to DISABLED. Anything else, Commander?
        IsAlien: true
        MarkInteractionComplete: false
        KeepOpen: true
        EnablingConditionTest: AllFalse
        EnablingConditions:
          - $: GcMissionConditionStatLevel
            Stat: <%= Atlas.Mod.Stat('CFG_CHAT') %>
            Level: 0
            Test: Equal
        Rewards:
          - Id: <%= Atlas.Reward('CHT_OFF') %>
            RewardChoice: GiveAll
            List:
              - $: GcRewardModifyStat
                Stat: <%= Atlas.Mod.Stat('CFG_CHAT') %>
                ModifyType: Set
                Amount: 1
          # - <%= Atlas.Reward('REBOOT') %>

      - Name: <%= Atlas.Mod.LocKey('MENU_OPT_HOME') %>
        NextInteraction: <%= Atlas.Config.HomeDialogId %>
        SelectedOnBackOut: true
        KeepOpen: true
