SearchGroups:
  SVG:
    FlybyId: 1
    Cost: LG
    Events:
      - DPOD
      - DIST
      - DPOT
      - CRFR
      - RBCP
      - DRCS
      - FACT
      - HARV

  BLD:
    FlybyId: 2
    Cost: SM
    Events:
      - SHLT
      - TERM
      - SHOP
      - BASE
      - OUTP
      - LBRY
      - SETL

  ANC:
    FlybyId: 3
    Cost: MD
    Events:
      - PLAQ
      - MONO
      - PORT
      - ABAN
      - RUIN
      - TREA
      - GRV
      - GLCH

  SIG:
    FlybyId: 4
    Cost: SM
    Events:
      # - BEAC
      - DRHV
      - RDIO
      - OBSV
      - DNPC
      - MTOW

  UW:
    FlybyId: 5
    Cost: SM
    Events:
      - UWAB
      - UWDS
      - UWCF
      - UWTR
